### ISSUE TITLE
REALL Good but...

### ISSUE THREAD

**Issue by Pdzly** [WilliamVenner/gmsv_reqwest#1]
how do i use it? 
Like the syntax / usage / return of functions

**Comment by TomDotBat** [comment]
🤔🤔 `This module is a drop-in replacement for Garry's Mod's HTTP function` 🤔🤔

**Comment by WilliamVenner** [comment]
There is a usage section in the README. Everything is exactly the same as the HTTP function which comes with Gmod.

**Comment by Pdzly** [comment]
But whats the plus like its better like the buildtin thing or better performance

**Comment by WilliamVenner** [comment]
I don't know the internals of ISteamHTTP but I would imagine that this is better at running and processing http requests in parallel. The main purpose of this module is to provide more control over http requests (for example you cannot set the User-Agent header with gmod http)
