### ISSUE TITLE
Conflict: Srlion's Hook Library

### ISSUE THREAD

**Issue by FelixKLG** [WilliamVenner/gmsv_reqwest#3]
Architecture: Linux 32 bit

https://steamcommunity.com/sharedfiles/filedetails/?id=1907060869

If gmsv_reqwest is installed alongside Srlion's Hook library (on Linux 32 - no other tests have been carried out as of yet) the console gets consumed with the error 
`[Srlion's Hook Library] attempt to index a string value
1. func - [C]:-1
2. unknown - lua/includes/modules/hook.lua:241`

**Comment by WilliamVenner** [comment]
Yeah this isn't anything to do with srlion's hook library, this is an error inside gmsv_reqwest itself, but the error is tagged as srlions addon because its part of the stack trace

**Comment by WilliamVenner** [comment]
Do you possibly know when this occurs, what triggers it?

**Comment by FelixKLG** [comment]
I know the error is thrown when someone says something, someone join the server and some other things I haven't been able to narrow down the cause of.

I have attached a screenshot of the libraries I have installed.
(small note, I am testing to see possible conflicts now so I shall reply if I find it.)

![image](https://user-images.githubusercontent.com/44820580/130324820-18fcf621-af61-4437-8978-d6fbc2fbc155.png)

**Comment by FelixKLG** [comment]
some testing later, I have discovered it is bLogs and reqwest mixing.
I presume this is due to the Discord Relay.

**Comment by WilliamVenner** [comment]
I'll see if i can replicate

**Comment by WilliamVenner** [comment]
Give v0.2.1 a try

https://github.com/WilliamVenner/gmsv_reqwest/actions/runs/1153815430

**Comment by FelixKLG** [comment]
![image](https://user-images.githubusercontent.com/44820580/130326869-1df327e0-c193-4914-b5f8-37cd942587ee.png)
I restarted with the latest build of Reqwest and the issue is persisting.

**Comment by FelixKLG** [comment]
I have proformed another test, if I disable bLogs's Discord relaying features (properly this time xD) the errors don't occur

**Comment by WilliamVenner** [comment]
@FelixKLG Can you test if the problem still occurs now with v0.2.2?

**Comment by FelixKLG** [comment]
I will check shortly.

**Comment by RockerOfWorlds** [comment]
> @FelixKLG Can you test if the problem still occurs now with v0.2.2?

I've noticed this issue as well with the latest version v.0.2.2.
![image](https://user-images.githubusercontent.com/10678198/133091229-845bad81-8585-479e-9eda-fb9900d2bcfe.png)

**Comment by FelixKLG** [comment]
sorry for late reply, ADHD and life got the better of me.
I can confirm that this still does occur.
![image](https://user-images.githubusercontent.com/44820580/133528593-47085a46-8cb6-4986-9959-061af178e5ef.png)

**Comment by WilliamVenner** [comment]
Also are you sure that Srlion's Hook Library is the common denominator here, or does it still occur when that's uninstalled?

**Comment by FelixKLG** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2603756896
https://uploadi.ng/upload/Nqnn5FSn

after some further testing spurred on by your prior comment, I now know it's bLogs Discord webhook.

if anything happens which blogs has to send in a webhook it seems to print the error.

with blogs is not installed nothing is using reqwest so nothing cuases the error.

**Comment by WilliamVenner** [comment]
bLogs Discord webhook would be the only thing using reqwest in that context, no?

**Comment by FelixKLG** [comment]
it is the only thing that uses it, yes.

what I had to recreate the error:

bLogs
Xeon
SAM
SUI
Reqwest
Srlion Hook Lib
Gmod Admin Suite

bLogs Discord Webhook on chat events.

**Comment by WilliamVenner** [comment]
Does the error occur when Srlion's hook lib is not installed?

**Comment by FelixKLG** [comment]
yes actually,
sorry I though I had tested that.

```
FelixKLG: test
[ERROR] attempt to index a string value
1. v - [C]:-1
2. unknown - lua/includes/modules/hook.lua:84
FelixKLG: test
[ERROR] attempt to index a string value
1. v - [C]:-1
2. unknown - lua/includes/modules/hook.lua:84
```

**Comment by ghost** [comment]
Do something about this please..

**Comment by FelixKLG** [comment]
@avaster303 though it would be nice if this were to not be the case I wish to iterate this is open-source software with an "AS-IS" license thereby giving Mr. Venner as much time as he wishes to deal with this; or not as the case may be.
If this is really effecting you so much I suggest you endeavor to educate yourself on the Rust language and open a pull request if you find a patch.

**Comment by WilliamVenner** [comment]
Managed to reproduce the problem and fix it for good
