### ISSUE TITLE
Game crash on require("reqwest")

### ISSUE THREAD

**Issue by wrefgtzweve** [WilliamVenner/gmsv_reqwest#6]
My game crashes instantly whenever i do require("reqwest") on serverside, tried in p2p and singleplayer, no crash logs are generated. Any idea what could cause this?

**Comment by WilliamVenner** [comment]
What OS?

**Comment by wrefgtzweve** [comment]
windows 64 bit
![image](https://user-images.githubusercontent.com/69946827/152412665-5add779d-7afa-4169-b0db-9b0b80843839.png)

**Comment by wrefgtzweve** [comment]
tried v3 and v2.0.1, both crash

**Comment by WilliamVenner** [comment]
Idk man, works fine for me

```lua
] lua_run_cl require("reqwest")
] lua_run_cl print(reqwest)
function: 0x01e7affea9c0

] lua_run require("reqwest")
> require("reqwest")...
] lua_run print(reqwest)
> print(reqwest)...
function: 0x01e7b04fb638
```

**Comment by WilliamVenner** [comment]
Also works on main branch

**Comment by wrefgtzweve** [comment]
is that on p2p? i'll try on a dedicated server

**Comment by WilliamVenner** [comment]
Singleplayer

**Comment by wrefgtzweve** [comment]
Tested it on a dedicated server (Linux x86), worked fine. Might be a windows issue? I'm on Windows x86-64

**Comment by WilliamVenner** [comment]
Yeah, that's what I tested on

**Comment by wrefgtzweve** [comment]
Closing this because I can't get any additional info, I'll reopen if I ever find new info.
